
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 26 2023 16:00:11 IST (Apr 26 2023 10:30:11 UTC)

// Verification Directory fv/ascon_lut 

module ascon_lut(x, y);
  input [4:0] x;
  output [4:0] y;
  wire [4:0] x;
  wire [4:0] y;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_10, n_11, n_12, n_13, n_16;
  OAI21M1S g242(.A1 (n_1), .A2 (n_4), .B (n_16), .Z (y[3]));
  AOI31M1S g243(.A1 (n_11), .A2 (x[2]), .A3 (x[3]), .B (n_2), .Z
       (n_16));
  MXB2M1SA g245(.A (n_6), .B (n_10), .S (x[3]), .Z (y[4]));
  MOAI22M1SA g244(.A1 (n_13), .A2 (n_12), .B1 (n_13), .B2 (n_12), .Z
       (y[1]));
  AO21M1SA g246(.A1 (n_10), .A2 (x[4]), .B (n_13), .Z (n_11));
  AO22M1SA g249(.A1 (x[3]), .A2 (n_5), .B1 (n_10), .B2 (n_3), .Z
       (y[0]));
  NR2M1S g250(.A (x[4]), .B (n_10), .Z (n_13));
  MOAI22M1SA g248(.A1 (n_12), .A2 (n_7), .B1 (n_12), .B2 (n_7), .Z
       (y[2]));
  MAOI22M2SA g251(.A1 (n_5), .A2 (x[2]), .B1 (n_5), .B2 (x[2]), .Z
       (n_6));
  AOI21M1S g252(.A1 (n_3), .A2 (x[1]), .B (n_12), .Z (n_4));
  NR4B1M1S g247(.B (x[2]), .C (x[1]), .D (x[3]), .NA (n_1), .Z (n_2));
  OAI21B01M1S g254(.A1 (x[0]), .A2 (n_0), .NB (n_7), .Z (n_10));
  MXB2M1SA g255(.A (x[1]), .B (n_0), .S (x[4]), .Z (n_5));
  MXB2M1SA g256(.A (n_3), .B (x[3]), .S (x[2]), .Z (n_12));
  MAOI22M2SA g253(.A1 (x[4]), .A2 (x[0]), .B1 (x[4]), .B2 (x[0]), .Z
       (n_1));
  AN2M2S g257(.A (n_0), .B (x[0]), .Z (n_7));
  CKINVM1S g258(.A (x[3]), .Z (n_3));
  CKINVM1S g259(.A (x[1]), .Z (n_0));
endmodule

