
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 26 2023 16:13:51 IST (Apr 26 2023 10:43:51 UTC)

// Verification Directory fv/ascon_kmap 

module ascon_kmap(x, y);
  input [4:0] x;
  output [4:0] y;
  wire [4:0] x;
  wire [4:0] y;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_9;
  wire n_10, n_12, n_13;
  MXB2M1SA g377(.A (n_6), .B (n_7), .S (x[3]), .Z (y[4]));
  MOAI22M1SA g378(.A1 (n_13), .A2 (n_12), .B1 (n_13), .B2 (n_12), .Z
       (y[1]));
  MOAI22M1SA g376(.A1 (n_10), .A2 (n_9), .B1 (n_10), .B2 (n_9), .Z
       (y[3]));
  AO22M1SA g380(.A1 (x[3]), .A2 (n_5), .B1 (n_7), .B2 (n_1), .Z (y[0]));
  MAOI22M2SA g384(.A1 (n_5), .A2 (x[2]), .B1 (n_5), .B2 (x[2]), .Z
       (n_6));
  MOAI22M1SA g381(.A1 (n_12), .A2 (n_3), .B1 (n_12), .B2 (n_3), .Z
       (y[2]));
  NR2M1S g382(.A (x[4]), .B (n_7), .Z (n_13));
  OAI21B01M1S g386(.A1 (x[0]), .A2 (n_2), .NB (n_3), .Z (n_7));
  OAI31M1S g379(.A1 (x[2]), .A2 (x[3]), .A3 (x[1]), .B (n_0), .Z
       (n_10));
  MXB2M1SA g387(.A (x[1]), .B (n_2), .S (x[4]), .Z (n_5));
  MXB2M1SA g388(.A (n_1), .B (x[3]), .S (x[2]), .Z (n_12));
  MAOI22M2SA g385(.A1 (x[4]), .A2 (x[0]), .B1 (x[4]), .B2 (x[0]), .Z
       (n_9));
  ND3M1S g383(.A (x[1]), .B (x[2]), .C (x[3]), .Z (n_0));
  AN2M2S g389(.A (n_2), .B (x[0]), .Z (n_3));
  CKINVM1S g390(.A (x[3]), .Z (n_1));
  CKINVM1S g391(.A (x[1]), .Z (n_2));
endmodule

