
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 26 2023 16:00:38 IST (Apr 26 2023 10:30:38 UTC)

// Verification Directory fv/ascon_anf 

module ascon_anf(x, y);
  input [4:0] x;
  output [4:0] y;
  wire [4:0] x;
  wire [4:0] y;
  wire n_0, n_1, n_2, n_3, n_4, n_6, n_7, n_8;
  wire n_9, n_11, n_12, n_14;
  OAI222M1SA g315(.A1 (x[3]), .A2 (n_3), .B1 (n_7), .B2 (n_8), .C1
       (n_14), .C2 (n_9), .Z (y[4]));
  MXB3M1SA g319(.A (n_14), .B (n_1), .C (n_6), .S0 (x[1]), .S1 (n_0),
       .Z (y[3]));
  MOAI22M1SA g316(.A1 (n_12), .A2 (n_11), .B1 (n_12), .B2 (n_11), .Z
       (y[1]));
  AO22M1SA g318(.A1 (x[3]), .A2 (n_9), .B1 (n_8), .B2 (n_7), .Z (y[0]));
  AOI221M1S g322(.A1 (n_2), .A2 (x[3]), .B1 (n_7), .B2 (x[1]), .C
       (n_11), .Z (n_6));
  MOAI22M1SA g317(.A1 (n_11), .A2 (n_4), .B1 (n_11), .B2 (n_4), .Z
       (y[2]));
  NR2M1S g320(.A (x[4]), .B (n_8), .Z (n_12));
  ND2M1S g321(.A (n_9), .B (x[2]), .Z (n_3));
  OAI21B01M1S g323(.A1 (x[0]), .A2 (n_2), .NB (n_4), .Z (n_8));
  MXB2M1SA g326(.A (x[1]), .B (n_2), .S (x[4]), .Z (n_9));
  AN2M2S g324(.A (n_14), .B (n_1), .Z (n_11));
  MOAI22M1SA g325(.A1 (x[4]), .A2 (x[0]), .B1 (x[4]), .B2 (x[0]), .Z
       (n_0));
  AN2M2S g328(.A (n_2), .B (x[0]), .Z (n_4));
  ND2M1S g327(.A (x[3]), .B (x[2]), .Z (n_1));
  OR2M2S g329(.A (x[2]), .B (x[3]), .Z (n_14));
  CKINVM1S g330(.A (x[3]), .Z (n_7));
  CKINVM1S g331(.A (x[1]), .Z (n_2));
endmodule

