
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  1 2023 10:59:02 IST (May  1 2023 05:29:02 UTC)

// Verification Directory fv/round_constant 

module round_constant(clk, start, rst, rounds, r_con, done, init);
  input clk, start, rst;
  input [3:0] rounds;
  output [7:0] r_con;
  output done, init;
  wire clk, start, rst;
  wire [3:0] rounds;
  wire [7:0] r_con;
  wire done, init;
  wire [3:0] count;
  wire csa_tree_sub_43_50_groupi_n_0, csa_tree_sub_43_50_groupi_n_1,
       csa_tree_sub_43_50_groupi_n_2, csa_tree_sub_43_50_groupi_n_3,
       csa_tree_sub_43_50_groupi_n_4, csa_tree_sub_43_50_groupi_n_5,
       csa_tree_sub_43_50_groupi_n_6, csa_tree_sub_43_50_groupi_n_7;
  wire csa_tree_sub_43_50_groupi_n_8, csa_tree_sub_43_50_groupi_n_9,
       csa_tree_sub_43_50_groupi_n_10, csa_tree_sub_43_50_groupi_n_11,
       csa_tree_sub_43_50_groupi_n_12, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_17, n_18, n_19;
  wire n_20, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_81, n_82, n_589_BAR;
  assign count[0] = 1'b0;
  assign count[1] = 1'b0;
  assign count[2] = 1'b0;
  assign count[3] = 1'b0;
  assign init = 1'b0;
  INVM2S g683(.A (n_70), .Z (n_72));
  ADHM1SA g684(.A (n_69), .B (rounds[3]), .CO (n_73), .S (n_70));
  OAI21M2S g685(.A1 (rounds[1]), .A2 (rounds[2]), .B (n_68), .Z (n_71));
  ND2M1S g686(.A (rounds[3]), .B (rounds[2]), .Z (n_589_BAR));
  INVM2S g687(.A (n_68), .Z (n_69));
  ND2M1S g688(.A (rounds[2]), .B (rounds[1]), .Z (n_68));
  INVM2S g689(.A (rounds[0]), .Z (n_81));
  DFQM2SA \r_con_reg[7] (.CK (clk), .D (n_67), .Q (r_con[7]));
  AO22M1SA g1651(.A1 (n_43), .A2 (n_65), .B1 (r_con[7]), .B2 (n_4), .Z
       (n_67));
  DFQM2SA \r_con_reg[6] (.CK (clk), .D (n_66), .Q (r_con[6]));
  MOAI22M1SA g1653(.A1 (n_63), .A2 (n_44), .B1 (r_con[6]), .B2 (n_4),
       .Z (n_66));
  XOR3M1SA g1654(.A (n_30), .B (n_37), .C (n_61), .Z (n_65));
  DFQM2SA \r_con_reg[5] (.CK (clk), .D (n_64), .Q (r_con[5]));
  DFQM2SA \r_con_reg[4] (.CK (clk), .D (n_62), .Q (r_con[4]));
  AO22M1SA g1657(.A1 (n_43), .A2 (n_60), .B1 (r_con[5]), .B2 (n_4), .Z
       (n_64));
  AOI21M1S g1658(.A1 (n_59), .A2 (n_52), .B (n_61), .Z (n_63));
  AO22M1SA g1659(.A1 (n_43), .A2 (n_58), .B1 (r_con[4]), .B2 (n_4), .Z
       (n_62));
  NR2M1S g1660(.A (n_52), .B (n_59), .Z (n_61));
  MOAI22M1SA g1661(.A1 (n_55), .A2 (n_56), .B1 (n_55), .B2 (n_56), .Z
       (n_60));
  NR2B1M1S g1662(.B (n_53), .NA (n_55), .Z (n_59));
  MOAI22M1SA g1663(.A1 (n_57), .A2 (n_40), .B1 (n_57), .B2 (n_40), .Z
       (n_58));
  DFQM2SA \r_con_reg[3] (.CK (clk), .D (n_54), .Q (r_con[3]));
  DFQM2SA \count_reg[3] (.CK (clk), .D (n_49), .Q (count[3]));
  DFQM2SA \count_reg[2] (.CK (clk), .D (n_48), .Q (count[2]));
  DFQM2SA \count_reg[1] (.CK (clk), .D (n_51), .Q (count[1]));
  DFQM2SA \r_con_reg[0] (.CK (clk), .D (n_50), .Q (r_con[0]));
  DFQM2SA \r_con_reg[1] (.CK (clk), .D (n_47), .Q (r_con[1]));
  DFQM2SA \r_con_reg[2] (.CK (clk), .D (n_46), .Q (r_con[2]));
  SDFQM2SA \count_reg[0] (.CK (clk), .D (n_43), .SD (n_4), .SE
       (count[0]), .Q (count[0]));
  MOAI22M1SA g1672(.A1 (n_44), .A2 (n_41), .B1 (r_con[3]), .B2 (n_4),
       .Z (n_54));
  MAOI22M2SA g1673(.A1 (n_42), .A2 (n_7), .B1 (n_42), .B2 (n_7), .Z
       (n_57));
  AO21M1SA g1674(.A1 (n_38), .A2 (n_23), .B (n_53), .Z (n_56));
  OAI21M1S g1675(.A1 (n_7), .A2 (n_40), .B (n_42), .Z (n_55));
  AO22M1SA g1676(.A1 (n_10), .A2 (n_43), .B1 (n_4), .B2 (count[1]), .Z
       (n_51));
  NR2M1S g1677(.A (n_23), .B (n_38), .Z (n_53));
  DFQM2SA done_reg(.CK (clk), .D (n_45), .Q (done));
  NR2M1S g1679(.A (n_31), .B (n_38), .Z (n_52));
  MOAI22M1SA g1680(.A1 (n_44), .A2 (n_7), .B1 (r_con[0]), .B2 (n_4), .Z
       (n_50));
  AO22M1SA g1681(.A1 (n_24), .A2 (n_43), .B1 (n_4), .B2 (count[3]), .Z
       (n_49));
  AO22M1SA g1682(.A1 (n_18), .A2 (n_43), .B1 (n_4), .B2 (count[2]), .Z
       (n_48));
  MOAI22M1SA g1683(.A1 (n_44), .A2 (n_28), .B1 (r_con[1]), .B2 (n_4),
       .Z (n_47));
  MOAI22M1SA g1684(.A1 (n_44), .A2 (n_34), .B1 (r_con[2]), .B2 (n_4),
       .Z (n_46));
  OAI22B10M1S g1685(.A1 (n_15), .B1 (n_5), .B2 (n_39), .NA2 (done), .Z
       (n_45));
  INVM2S g1686(.A (n_44), .Z (n_43));
  ND2B1M2S g1687(.B (n_39), .NA (n_5), .Z (n_44));
  AOI21M1S g1688(.A1 (n_32), .A2 (n_37), .B (n_40), .Z (n_41));
  AOI21M1S g1689(.A1 (n_36), .A2 (n_26), .B (n_38), .Z (n_42));
  NR2M1S g1690(.A (n_37), .B (n_32), .Z (n_40));
  ND3B1M1S g1691(.B (n_22), .C (n_7), .NA (n_35), .Z (n_39));
  NR2M1S g1692(.A (n_26), .B (n_36), .Z (n_38));
  ADFM1SA g1693(.A (n_0), .B (n_27), .CI (n_29), .CO (n_36), .S (n_37));
  OAI211M1S g1694(.A1 (n_11), .A2 (n_12), .B (n_33), .C (n_82), .Z
       (n_35));
  OA21M1SA g1695(.A1 (n_31), .A2 (n_25), .B (n_32), .Z (n_34));
  MAOI22M2SA g1696(.A1 (n_8), .A2 (n_27), .B1 (n_8), .B2 (n_27), .Z
       (n_33));
  ND2M1S g1697(.A (n_31), .B (n_25), .Z (n_32));
  INVM2S g1698(.A (n_30), .Z (n_31));
  ADFM1SA g1699(.A (n_18), .B (rounds[2]), .CI (n_20), .CO (n_29), .S
       (n_30));
  AOI21B10M1S g1700(.A1 (n_7), .B (n_25), .NA2 (n_23), .Z (n_28));
  MAOI22M2SA g1701(.A1 (rounds[3]), .A2 (n_24), .B1 (rounds[3]), .B2
       (n_24), .Z (n_27));
  ND2B1M2S g1702(.B (rounds[3]), .NA (n_24), .Z (n_26));
  NR2B1M1S g1703(.B (n_7), .NA (n_23), .Z (n_25));
  DFQM2SA init_reg(.CK (clk), .D (n_19), .Q (init));
  MOAI22M1SA g1705(.A1 (count[3]), .A2 (n_9), .B1 (count[3]), .B2
       (n_9), .Z (n_24));
  MAOI22M2SA g1706(.A1 (n_12), .A2 (n_11), .B1 (n_6), .B2 (n_589_BAR),
       .Z (n_22));
  MAOI22M2SA g1708(.A1 (n_17), .A2 (n_1), .B1 (n_17), .B2 (n_1), .Z
       (n_23));
  AO21M1SA g1709(.A1 (n_13), .A2 (n_1), .B (n_14), .Z (n_20));
  AO21M1SA g1710(.A1 (n_5), .A2 (init), .B (n_15), .Z (n_19));
  INVM2S g1711(.A (n_11), .Z (n_18));
  ND2B1M2S g1713(.B (n_13), .NA (n_14), .Z (n_17));
  NR4B1M1S g1714(.B (count[3]), .C (count[2]), .D (n_5), .NA (n_3), .Z
       (n_15));
  NR2B1M1S g1715(.B (rounds[1]), .NA (n_10), .Z (n_14));
  ND2B1M2S g1716(.B (rounds[1]), .NA (n_10), .Z (n_13));
  AOI21B01M1S g1717(.A1 (n_6), .A2 (n_0), .NB (n_8), .Z (n_12));
  OAI21B10M1S g1718(.A1 (count[2]), .B (n_9), .NA2 (n_2), .Z (n_11));
  NR2B1M1S g1719(.B (n_3), .NA (n_2), .Z (n_10));
  ND2B1M1S g1720(.B (count[2]), .NA (n_2), .Z (n_9));
  OR2M2S g1721(.A (n_0), .B (n_6), .Z (n_8));
  OAI21M1S g1722(.A1 (count[0]), .A2 (rounds[0]), .B (n_1), .Z (n_7));
  ND2M1S g1723(.A (rounds[1]), .B (rounds[0]), .Z (n_6));
  ND2B1M2S g1724(.B (start), .NA (rst), .Z (n_5));
  NR2M1S g1725(.A (rst), .B (start), .Z (n_4));
  NR2M1S g1726(.A (count[1]), .B (count[0]), .Z (n_3));
  ND2M1S g1727(.A (count[0]), .B (count[1]), .Z (n_2));
  ND2M1S g1728(.A (rounds[0]), .B (count[0]), .Z (n_1));
  INVM2S g1729(.A (rounds[2]), .Z (n_0));
  INVM2S csa_tree_sub_43_50_groupi_g92(.A (n_81), .Z (r_con[0]));
  OAI22M1S csa_tree_sub_43_50_groupi_g343(.A1 (n_72), .A2
       (csa_tree_sub_43_50_groupi_n_12), .B1 (n_71), .B2
       (csa_tree_sub_43_50_groupi_n_10), .Z (r_con[7]));
  AO211M2SA csa_tree_sub_43_50_groupi_g344(.A1
       (csa_tree_sub_43_50_groupi_n_9), .A2 (n_71), .B
       (csa_tree_sub_43_50_groupi_n_11), .C
       (csa_tree_sub_43_50_groupi_n_4), .Z (r_con[6]));
  NR3B1M1S csa_tree_sub_43_50_groupi_g345(.B (r_con[0]), .C (n_71), .NA
       (csa_tree_sub_43_50_groupi_n_9), .Z
       (csa_tree_sub_43_50_groupi_n_12));
  OAI22M1S csa_tree_sub_43_50_groupi_g346(.A1 (rounds[1]), .A2
       (csa_tree_sub_43_50_groupi_n_7), .B1 (n_73), .B2
       (csa_tree_sub_43_50_groupi_n_8), .Z (r_con[5]));
  NR2M1S csa_tree_sub_43_50_groupi_g347(.A (n_71), .B
       (csa_tree_sub_43_50_groupi_n_9), .Z
       (csa_tree_sub_43_50_groupi_n_11));
  ND2M1S csa_tree_sub_43_50_groupi_g348(.A
       (csa_tree_sub_43_50_groupi_n_9), .B (n_72), .Z
       (csa_tree_sub_43_50_groupi_n_10));
  MOAI22M1SA csa_tree_sub_43_50_groupi_g349(.A1
       (csa_tree_sub_43_50_groupi_n_6), .A2
       (csa_tree_sub_43_50_groupi_n_0), .B1
       (csa_tree_sub_43_50_groupi_n_6), .B2
       (csa_tree_sub_43_50_groupi_n_0), .Z (r_con[4]));
  OA21M1SA csa_tree_sub_43_50_groupi_g350(.A1
       (csa_tree_sub_43_50_groupi_n_2), .A2 (n_81), .B
       (csa_tree_sub_43_50_groupi_n_6), .Z
       (csa_tree_sub_43_50_groupi_n_8));
  NR3M1S csa_tree_sub_43_50_groupi_g351(.A (rounds[1]), .B (n_81), .C
       (n_73), .Z (csa_tree_sub_43_50_groupi_n_9));
  OAI21B10M1S csa_tree_sub_43_50_groupi_g352(.A1
       (csa_tree_sub_43_50_groupi_n_5), .B
       (csa_tree_sub_43_50_groupi_n_6), .NA2 (n_72), .Z (r_con[3]));
  AOI21B10M1S csa_tree_sub_43_50_groupi_g353(.A1 (n_73), .B
       (csa_tree_sub_43_50_groupi_n_0), .NA2
       (csa_tree_sub_43_50_groupi_n_4), .Z
       (csa_tree_sub_43_50_groupi_n_7));
  ND2M1S csa_tree_sub_43_50_groupi_g354(.A
       (csa_tree_sub_43_50_groupi_n_4), .B
       (csa_tree_sub_43_50_groupi_n_2), .Z
       (csa_tree_sub_43_50_groupi_n_6));
  AO21M1SA csa_tree_sub_43_50_groupi_g355(.A1 (n_71), .A2
       (csa_tree_sub_43_50_groupi_n_3), .B
       (csa_tree_sub_43_50_groupi_n_5), .Z (r_con[2]));
  NR2M1S csa_tree_sub_43_50_groupi_g356(.A (rounds[1]), .B
       (csa_tree_sub_43_50_groupi_n_1), .Z
       (csa_tree_sub_43_50_groupi_n_5));
  NR2M1S csa_tree_sub_43_50_groupi_g357(.A (n_72), .B
       (csa_tree_sub_43_50_groupi_n_1), .Z
       (csa_tree_sub_43_50_groupi_n_4));
  MXB2M1SA csa_tree_sub_43_50_groupi_g358(.A (rounds[1]), .B
       (csa_tree_sub_43_50_groupi_n_2), .S (n_81), .Z (r_con[1]));
  ND2M1S csa_tree_sub_43_50_groupi_g360(.A (r_con[0]), .B
       (csa_tree_sub_43_50_groupi_n_2), .Z
       (csa_tree_sub_43_50_groupi_n_3));
  INVM2S csa_tree_sub_43_50_groupi_g364(.A (rounds[1]), .Z
       (csa_tree_sub_43_50_groupi_n_2));
  ND2B1M2S csa_tree_sub_43_50_groupi_g2(.B (r_con[0]), .NA (n_71), .Z
       (csa_tree_sub_43_50_groupi_n_1));
  XOR2M2SA csa_tree_sub_43_50_groupi_g365(.A (n_81), .B (n_73), .Z
       (csa_tree_sub_43_50_groupi_n_0));
  XNR2M2SA g2(.A (n_17), .B (rounds[0]), .Z (n_82));
endmodule

